** 目录

**  [[#空格]]
*** [[*中英文之间需要增加空格][中英文之间需要增加空格]]
*** [[*中文与数字之间需要增加空格][中文与数字之间需要增加空格]]
*** [[*数字与单位之间需要增加空格][数字与单位之间需要增加空格]]
*** [[*全角标点与其他字符之间不加空格][全角标点与其他字符之间不加空格]]
*** [[**-ms-text-autospace* to the rescue?][*-ms-text-autospace* to the rescue?]]
** [[*全角和半角][全角和半角]]
*** [[*使用全角中文标点][使用全角中文标点]]
*** [[*数字使用半角字符][数字使用半角字符]] 
*** [[*遇到完整的英文整句、特殊名词，其內容使用半角标点][遇到完整的英文整句、特殊名词，其內容使用半角标点]]
** [[*名词][名词]]
*** [[*专有名词使用正确的大小写][专有名词使用正确的大小写]]
*** [[*不要使用不地道的缩写][不要使用不地道的缩写]]
** [[*争议][争议]]
*** [[*链接之间增加空格][链接之间增加空格]]
*** [[*简体中文使用直角引号][简体中文使用直角引号]]
** [[*参考文献][参考文献]]
   -----
** 空格
   #+BEGIN_QUOTE
   有研究显示，打字的时候不喜欢在中文和英文之间加空格的人，感情路都走得很辛苦，有七成的比例会在 34 岁的时候跟自己不爱的人结婚，而其余三成的人最后只能把遗产留给自己的猫。毕竟爱情跟书写都需要适时地留白。
   与大家共勉之。 [[https://github.com/vinta/pangu.js][vinta/paranoid-auto-spacing]]
   #+END_QUOTE
*** 中英文之间需要增加空格

    正确：
    #+BEGIN_QUOTE
    在 LeanCloud 上，数据存储是围绕 `AVObject` 进行的。
    #+END_QUOTE

    错误：
    #+BEGIN_QUOTE
    在LeanCloud上，数据存储是围绕`AVObject`进行的。
    #+END_QUOTE
    #+BEGIN_QUOTE
    在 LeanCloud上，数据存储是围绕`AVObject` 进行的。
    #+END_QUOTE

    完整的正确用法：
    #+BEGIN_QUOTE
    在 LeanCloud 上，数据存储是围绕 `AVObject` 进行的。每个 `AVObject` 都包含了与 JSON 兼容的 key-value 对应的数据。数据是 schema-free 的，你不需要在每个 `AVObject` 上提前指定存在哪些键，只要直接设定对应的 key-value 即可。
    #+END_QUOTE

    例外：「豆瓣FM」等产品名词，按照官方所定义的格式书写。
*** 中文与数字之间需要增加空格

    正确：
    #+BEGIN_QUOTE
    今天出去买菜花了 5000 元。
    #+END_QUOTE
     

    错误：
    #+BEGIN_QUOTE
    今天出去买菜花了 5000元。
    #+END_QUOTE
    #+BEGIN_QUOTE
    今天出去买菜花了5000元。
    #+END_QUOTE
*** 数字与单位之间需要增加空格

    正确：

    #+BEGIN_QUOTE
    我家的光纤入户宽带有 10 Gbps，SSD 一共有 20 TB。
    #+END_QUOTE

    错误：

    #+BEGIN_QUOTE
    我家的光纤入户宽带有 10Gbps，SSD 一共有 10TB。
    #+END_QUOTE

    例外：度／百分比与数字之间不需要增加空格：

    正确：

    #+BEGIN_QUOTE
    今天是 233° 的高温。
    #+END_QUOTE

    #+BEGIN_QUOTE
    新 MacBook Pro 有 15% 的 CPU 性能提升。
    #+END_QUOTE

    错误：

    #+BEGIN_QUOTE
    今天是 233 ° 的高温。
    #+END_QUOTE

    #+BEGIN_QUOTE
    新 MacBook Pro 有 15 % 的 CPU 性能提升。
    #+END_QUOTE
*** 全角标点与其他字符之间不加空格

    正确：

    #+BEGIN_QUOTE
    刚刚买了一部 iPhone，好开心！
    #+END_QUOTE

    错误：

    #+BEGIN_QUOTE
    刚刚买了一部 iPhone ，好开心！
    #+END_QUOTE
*** *-ms-text-autospace* to the rescue?

    Microsoft 有个  [[https://msdn.microsoft.com/library/ms531164][-ms-text-autospace]]  的 CSS 属性可以实现自动为中英文之间增加空白。不过目前并未普及，另外在其他应用场景，例如 OS X、iOS 的用户界面目前并不存在这个特性，所以请继续保持随手加空格的习惯。
** 全角和半角
   不明白什么是全角（全形）与半角（半形）符号？请查看维基百科词条 [[https://zh.wikipedia.org/wiki/%25E5%2585%25A8%25E5%25BD%25A2%25E5%2592%258C%25E5%258D%258A%25E5%25BD%25A2][全角和半角]]
*** 使用全角中文标点

    正确：
    #+BEGIN_QUOTE
    嗨！你知道嘛？今天前台的小妹跟我说「喵」了哎！
    #+END_QUOTE
    #+BEGIN_QUOTE
    核磁共振成像（NMRI）是什么原理都不知道？JFGI！
    #+END_QUOTE


    错误：
    #+BEGIN_QUOTE
    嗨! 你知道嘛? 今天前台的小妹跟我说 "喵" 了哎!
    #+END_QUOTE

    #+BEGIN_QUOTE
    嗨!你知道嘛?今天前台的小妹跟我说"喵"了哎!
    #+END_QUOTE

    #+BEGIN_QUOTE
    核磁共振成像 (NMRI) 是什么原理都不知道? JFGI!
    #+END_QUOTE

    #+BEGIN_QUOTE
    核磁共振成像(NMRI)是什么原理都不知道?JFGI!
    #+END_QUOTE
*** 数字使用半角字符

    正确：

    #+BEGIN_QUOTE
    这件蛋糕只卖 1000 元。
    #+END_QUOTE

    错误：

    #+BEGIN_QUOTE
    这件蛋糕只卖 １０００ 元。
    #+END_QUOTE

    例外：在设计稿、宣传海报中如出现极少量数字的情形时，为方便文字对齐，是可以使用全角数字的。
*** 遇到完整的英文整句、特殊名词，其內容使用半角标点

    正确：
    #+BEGIN_QUOTE
    乔布斯那句话是怎么说的？「Stay hungry, stay foolish.」
    #+END_QUOTE


    #+BEGIN_QUOTE
    推荐你阅读《Hackers & Painters: Big Ideas from the Computer Age》，非常的有趣。
    #+END_QUOTE

    错误：

    #+BEGIN_QUOTE
     乔布斯那句话是怎么说的？「Stay hungry，stay foolish。」
    #+END_QUOTE

    #+BEGIN_QUOTE
    推荐你阅读《Hackers＆Painters：Big Ideas from the Computer Age》，非常的有趣。
    #+END_QUOTE
** 名词
*** 专有名词使用正确的大小写

    大小写相关用法原属于英文书写范畴，不属于本 wiki 讨论內容，在这里只对部分易错
    用法进行简述。备注：因为本项目主要是文章翻译，所以译者应该尽量遵循原文，但主
    要的尺度由译者作把握，本 wiki 只是给出建议

    正确：

    #+BEGIN_QUOTE
    使用 GitHub 登录
    #+END_QUOTE

    #+BEGIN_QUOTE
    我们的客户有 GitHub、Foursquare、Microsoft Corporation、Google、Facebook, Inc.。
    #+END_QUOTE

    错误：
    #+BEGIN_QUOTE
    使用 github 登录
    #+END_QUOTE

    #+BEGIN_QUOTE
    使用 GITHUB 登录
    #+END_QUOTE

    #+BEGIN_QUOTE
    使用 Github 登录
    #+END_QUOTE

    #+BEGIN_QUOTE
    使用 gitHub 登录
    #+END_QUOTE


    #+BEGIN_QUOTE
    使用 gｲんĤЦ8 登录
    #+END_QUOTE

    #+BEGIN_QUOTE
    我们的客户有 github、foursquare、microsoft corporation、google、facebook, inc.。
    #+END_QUOTE

    #+BEGIN_QUOTE
    我们的客户有 GITHUB、FOURSQUARE、MICROSOFT CORPORATION、GOOGLE、FACEBOOK, INC.。
    #+END_QUOTE

    #+BEGIN_QUOTE
    我们的客户有 Github、FourSquare、MicroSoft Corporation、Google、FaceBook, Inc.。
    #+END_QUOTE

    #+BEGIN_QUOTE
    我们的客户有 gitHub、fourSquare、microSoft Corporation、google、faceBook, Inc.。
    #+END_QUOTE

    #+BEGIN_QUOTE
    我们的客户有 gｲんĤЦ8、ｷouЯƧquﾑгє、๓เςг๏ร๏Ŧt ς๏гק๏гคtเ๏ภn、900913、ƒ4ᄃëв๏๏к, IПᄃ.。
    #+END_QUOTE

*** 不要使用不地道的缩写

    正确：
    #+BEGIN_QUOTE
    我们需要一位熟悉 JavaScript、HTML5，至少理解一种框架（如 Backbone.js、AngularJS、React 等）的前端开发者。
    #+END_QUOTE


    错误：

    #+BEGIN_QUOTE
    我们需要一位熟悉 Js、h5，至少理解一种框架（如 backbone、angular、RJS 等）的 FED。
    #+END_QUOTE

*** 专有名词的翻译
    一般而言，对于专有名词，建议尽量是不要翻译
** 争议
   以下用法略带有个人色彩，既：无论是否遵循下述规则，从语法的角度来讲都是 *正确* 的。
*** 链接之间增加空格

    用法：

    #+BEGIN_QUOTE
    请 [提交一个 issue](#) 并分配给相关同事。
    #+END_QUOTE
     
    #+BEGIN_QUOTE
    访问我们网站的最新动态，请 [点击这里](#) 进行订阅！
    #+END_QUOTE


    对比用法：
    #+BEGIN_QUOTE
    请[提交一个 issue](#) 并分配给相关同事。
    #+END_QUOTE


    #+BEGIN_QUOTE
    访问我们网站的最新动态，请[点击这里](#)进行订阅！
    #+END_QUOTE

*** 简体中文使用直角引号

    用法：

    #+BEGIN_QUOTE
    「老师，『有条不紊』的『紊』是什么意思？」
    #+END_QUOTE

    对比用法：

    #+BEGIN_QUOTE
    “老师，‘有条不紊’的‘紊’是什么意思？”
    #+END_QUOTE
     
** 参考文献

   - [[https://github.com/mzlogin/chinese-copywriting-guidelines][chinese-copywriting-guidelines]]
